### ISSUE TITLE
Choose Scripts - "Select All" only seems to run the first script.

### ISSUE THREAD

**Issue by iAlchemy** [soliantconsulting/fm-punisher#5]
When I select all scripts or simply choose multiple scripts I only seem to get results for the first script in the list.

Seems to be a US Date Format issue.

Changing the “_Date_convertTS” custom function to use dd/mm/yyyy hh:mm:ss instead of mm/dd/yyyy hh:mm:ss for locations not using the US Date format sorts it.

Alternatively you can update the “_Date_convertTS” custom function to use FileMaker Timestamp, Date and Time functions instead of a text substitution.

`				fromSQL ; 
					Let ([
						yyyy = Left ( ts ; 4 ) ; 
						mm = Middle (ts ; 6 ; 2 ) ; 
						dd = Middle ( ts ; 9 ;2 ) ; 
						hh = Middle ( ts ; 12 ; 2 );
						nn = Middle ( ts ; 15 ; 2 ) ; 
						ss = Middle ( ts ; 18 ; 2 )
						];Timestamp ( Date ( mm ; dd ; yyyy ) ; Time ( hh ; nn ; ss ) ) ) ; 

`

**Comment by iAlchemy** [comment]
Seems to be the same US Date Format issue.  

In the script "run_all_tests" I changed the definitions of $when_start and $when_stop to get the relevant timestamp values directly rather than via sql and "convert" to "fm" form (which is where the problem appears to be) and then replaced instances of getastimestamp ($when_stop) with simply $when_stop.

A more elegant solution may be to pass $when_start and $when_stop in as parameters.

Fundamentally I believe the custom function _Date_convertTS only works correctly on US Date Format systems.

**Comment by wimdecorte** [comment]
incorporated in next release.
