### ISSUE TITLE
Suggested error handling when no scripts selected

### ISSUE THREAD

**Issue by Jeraarts** [soliantconsulting/fm-punisher#6]
The script 'run_all_test' that runs via PSOS does not properly handle the scenario where no scripts are selected. Suggested check after line 61, please refer to image. I assumed all scripts were selected by default and did not check after installing the Punisher clone and had the issue where PSOS session where stuck. Event log mentioned error 104 (script not found) which was a good hint for the debug. The $scripts variable was empty but the first iteration of the inner loop was executed.
<img width="427" alt="image" src="https://user-images.githubusercontent.com/2738900/181354272-5961ca8c-b6e4-4c7d-845e-3c144bdfff9b.png">

**Comment by wimdecorte** [comment]
incorporated in next release.
