### ISSUE TITLE
credentials for punisher

### ISSUE THREAD

**Issue by MaxbizSolutions** [soliantconsulting/fm-punisher#8]
What is the username and password for punisher?
It won't open without entering a username and password.
I read through the documents but can't find the credentials.
I don't see a guest access option in my dialog box, so I can't use that.
I tried the following:
admin/admin
admin/Admin
admin/punisher
punisher/punisher

Thanks.

**Comment by wimdecorte** [comment]
It's listed in the readme under the "What do I need?" section
